name: jem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - shapely
  - tqdm
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - rasterio
  - seaborn
  - pip:
      - nismod-snail==0.5.2
      - gurobipy==11.0.3
      - snkit==1.9.0
      - -e .
